project_id = "swnhlzcodsnpsqpxaxov"

[functions.set-tour-password]
verify_jwt = true

[functions.verify-tour-password]
verify_jwt = false

[functions.validate-tour-access]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-weekly-reports]
verify_jwt = false

[functions.generate-tour-jwt]
verify_jwt = true

[functions.verify-tour-jwt]
verify_jwt = false

[functions.backup-processor]
verify_jwt = true

[functions.backup-worker]
verify_jwt = false

[functions.cloud-storage-auth]
verify_jwt = true

[functions.cloud-sync-worker]
verify_jwt = false
